import os
from datetime import datetime


def generate_pdf_report(image_path: str, record: dict) -> str:
    """Generate a PDF report using reportlab."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Image as RLImage,
        Table, TableStyle, HRFlowable
    )
    from reportlab.lib.enums import TA_CENTER, TA_LEFT

    output_path = os.path.join('static', 'reports', f"report_{record.get('id', 'x')}.pdf")
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=2*cm,
        bottomMargin=2*cm
    )

    styles = getSampleStyleSheet()
    green_dark = colors.HexColor('#043604')
    green_mid = colors.HexColor('#2d6a2d')
    green_light = colors.HexColor('#e8f5e9')

    # Custom styles
    title_style = ParagraphStyle(
        'Title', parent=styles['Title'],
        fontSize=22, textColor=green_dark,
        spaceAfter=6, alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    subtitle_style = ParagraphStyle(
        'Subtitle', parent=styles['Normal'],
        fontSize=11, textColor=green_mid,
        spaceAfter=4, alignment=TA_CENTER
    )
    section_style = ParagraphStyle(
        'Section', parent=styles['Heading2'],
        fontSize=13, textColor=green_dark,
        spaceBefore=12, spaceAfter=4,
        fontName='Helvetica-Bold'
    )
    body_style = ParagraphStyle(
        'Body', parent=styles['Normal'],
        fontSize=10, leading=16,
        spaceAfter=6
    )

    story = []

    # Header
    story.append(Paragraph("🌿 LeafMitra", title_style))
    story.append(Paragraph("AI Plant Disease Detection Report", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=2, color=green_mid, spaceAfter=12))

    # Metadata table
    timestamp = record.get('timestamp', datetime.now().strftime('%B %d, %Y %I:%M %p'))
    meta_data = [
        ['Report Generated:', timestamp],
        ['Detection Label:', record.get('label', 'N/A')],
        ['Confidence Score:', f"{record.get('confidence', 0):.1f}%"],
        ['Status:', 'Unknown / Low Confidence' if record.get('is_unknown') else 'Detected'],
    ]
    meta_table = Table(meta_data, colWidths=[5*cm, 12*cm])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), green_light),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [green_light, colors.white]),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 0.5*cm))

    # Uploaded Image
    if os.path.exists(image_path):
        story.append(Paragraph("Uploaded Leaf Image", section_style))
        try:
            img = RLImage(image_path, width=8*cm, height=8*cm)
            img.hAlign = 'CENTER'
            story.append(img)
        except Exception:
            story.append(Paragraph("(Image could not be embedded)", body_style))
        story.append(Spacer(1, 0.4*cm))

    # AI Insights
    story.append(HRFlowable(width="100%", thickness=1, color=green_light, spaceAfter=8))
    story.append(Paragraph("AI-Generated Insights", section_style))

    gemini_text = record.get('gemini_text', 'No insights available.')
    # Clean markdown for PDF
    clean_text = gemini_text.replace('**', '').replace('*', '•')
    for line in clean_text.split('\n'):
        line = line.strip()
        if line:
            if line.startswith('#'):
                story.append(Paragraph(line.lstrip('#').strip(), section_style))
            else:
                story.append(Paragraph(line, body_style))

    # Footer
    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=1, color=green_mid))
    story.append(Paragraph(
        "Generated by LeafMitra | AI Plant Disease Detection System | Team LeafMitra",
        ParagraphStyle('Footer', parent=styles['Normal'],
                       fontSize=8, textColor=colors.grey, alignment=TA_CENTER)
    ))

    doc.build(story)
    return output_path
